modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="reminisci"
version="1.0.0"
displayName="Reminisci"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="ultra_91rybsa, MCreator"

[[dependencies.reminisci]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




